import React,{useEffect,useMemo,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Upload,Plus,Trash2,Play,Download,Film,Music2,Sparkles,LoaderCircle}from'lucide-react';
import{FFmpeg}from'@ffmpeg/ffmpeg'; import{fetchFile,toBlobURL}from'@ffmpeg/util'; import'./style.css';

const beep=()=>{try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=620;g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.08);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.08)}catch{}};
const parseLRC=t=>t.split(/\r?\n/).flatMap(line=>{const m=[...line.matchAll(/\[(\d+):(\d+(?:\.\d+)?)\]/g)];const text=line.replace(/\[[^\]]+\]/g,'').trim();return m.map(x=>({time:+x[1]*60+ +x[2],text}))}).filter(x=>x.text).sort((a,b)=>a.time-b.time);
const fmt=s=>{s=Math.max(0,+s||0);return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`};
function App(){
 const [video,setVideo]=useState(null),[lrc,setLrc]=useState([]),[duration,setDuration]=useState(0),[segments,setSegments]=useState([{id:1,start:0,end:30,hook:'DÉCOUVERTE DU JOUR'}]),[active,setActive]=useState(1),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[status,setStatus]=useState('Prêt');
 const vid=useRef(),canvas=useRef(),logo=useRef(),final=useRef(); const seg=segments.find(x=>x.id===active)||segments[0];
 const lyrics=useMemo(()=>lrc, [lrc]);
 useEffect(()=>{let raf;const draw=()=>{const v=vid.current,c=canvas.current;if(v&&c&&v.readyState>=2){const x=c.getContext('2d'),W=1080,H=1920;x.fillStyle='#000';x.fillRect(0,0,W,H);const sw=v.videoWidth,sh=v.videoHeight,scale=Math.max(W/sw,H/sh),dw=sw*scale,dh=sh*scale;x.drawImage(v,(W-dw)/2,(H-dh)/2,dw,dh);const t=v.currentTime;if(seg&&t>=seg.start&&t<=seg.end){if(t<seg.start+2.6){x.fillStyle='rgba(0,0,0,.48)';x.fillRect(0,0,W,H);x.font='800 72px Arial';x.textAlign='center';x.fillStyle='white';wrap(x,seg.hook||'',540,840,900,86)} if(logo.current&&t<seg.end-2.7){const pulse=1+.035*Math.sin(performance.now()/350),w=250*pulse,h=w*(logo.current.naturalHeight/logo.current.naturalWidth);x.drawImage(logo.current,W-w-70,70,w,h)} const line=[...lyrics].reverse().find(a=>a.time<=t);if(line){x.font='700 58px Arial';x.textAlign='center';x.shadowColor='black';x.shadowBlur=14;x.fillStyle='white';wrap(x,line.text,540,1500,850,68);x.shadowBlur=0} if(t>=seg.end-2.7&&final.current)x.drawImage(final.current,0,0,W,H)}}raf=requestAnimationFrame(draw)};draw();return()=>cancelAnimationFrame(raf)},[seg,lyrics]);
 function wrap(x,text,cx,y,max,line){const words=text.split(' ');let l='',rows=[];for(const w of words){const q=l?l+' '+w:w;if(x.measureText(q).width>max&&l){rows.push(l);l=w}else l=q}if(l)rows.push(l);rows.slice(0,4).forEach((r,i)=>x.fillText(r,cx,y+i*line))}
 const upd=(k,val)=>setSegments(s=>s.map(x=>x.id===active?{...x,[k]:val}:x));
 const add=()=>{const id=Date.now();setSegments(s=>[...s,{id,start:0,end:Math.min(30,duration||30),hook:'NOUVEAU HOOK'}]);setActive(id);beep()};
 async function exportSeg(){if(!video||!seg)return;setBusy(true);setProgress(3);setStatus('Préparation du moteur vidéo…');try{const ff=new FFmpeg();ff.on('progress',({progress:p})=>setProgress(Math.max(5,Math.round(p*100))));const base='https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.12.10/dist/esm';await ff.load({coreURL:await toBlobURL(`${base}/ffmpeg-core.js`,'text/javascript'),wasmURL:await toBlobURL(`${base}/ffmpeg-core.wasm`,'application/wasm')});setStatus('Découpe et conversion 9:16…');const ext=video.name.split('.').pop()||'mp4';await ff.writeFile(`in.${ext}`,await fetchFile(video));await ff.exec(['-ss',String(seg.start),'-to',String(seg.end),'-i',`in.${ext}`,'-vf','scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920','-c:v','libx264','-preset','ultrafast','-crf','23','-c:a','aac','-movflags','+faststart','base.mp4']);const data=await ff.readFile('base.mp4');const url=URL.createObjectURL(new Blob([data.buffer],{type:'video/mp4'}));const a=document.createElement('a');a.href=url;a.download=`playoff_${fmt(seg.start).replace(':','-')}_${fmt(seg.end).replace(':','-')}.mp4`;a.click();setProgress(100);setStatus('Export terminé');beep()}catch(e){console.error(e);setStatus('Échec du rendu. Essaie un extrait plus court ou depuis ordinateur.')}finally{setBusy(false)}}
 return <div className="app"><header><img src="/logo.png"/><div><b>STUDIO</b><span>VERTICAL AUTOMATION</span></div><i></i></header><main><section className="panel inputs"><h2><Sparkles/> Projet</h2><label className="drop"><Film/><strong>{video?video.name:'Déposer la vidéo source'}</strong><small>MP4, MOV, WebM</small><input type="file" accept="video/*" onChange={e=>{const f=e.target.files[0];if(f){setVideo(f);beep()}}}/></label><label className="drop mini"><Music2/><strong>{lrc.length?`${lrc.length} lignes chargées`:'Déposer les paroles .LRC'}</strong><input type="file" accept=".lrc,text/plain" onChange={async e=>{const f=e.target.files[0];if(f)setLrc(parseLRC(await f.text()))}}/></label><div className="titleRow"><h2>Séquences</h2><button className="icon" onClick={add}><Plus/></button></div><div className="tabs">{segments.map((s,i)=><button onClick={()=>setActive(s.id)} className={s.id===active?'on':''}>#{String(i+1).padStart(2,'0')}</button>)}</div>{seg&&<div className="edit"><div className="times"><label>Début<input type="number" step=".1" value={seg.start} onChange={e=>upd('start',+e.target.value)}/></label><label>Fin<input type="number" step=".1" value={seg.end} onChange={e=>upd('end',+e.target.value)}/></label></div><label>Hook<textarea value={seg.hook} onChange={e=>upd('hook',e.target.value)} maxLength="90"/></label><button className="danger" disabled={segments.length===1} onClick={()=>{setSegments(s=>s.filter(x=>x.id!==active));setActive(segments.find(x=>x.id!==active)?.id)}}><Trash2/> Supprimer</button></div>}</section><section className="preview"><div className="phone"><canvas ref={canvas} width="1080" height="1920"/><video ref={vid} src={video?URL.createObjectURL(video):''} playsInline controls onLoadedMetadata={e=>{setDuration(e.currentTarget.duration);setSegments(s=>s.map((x,i)=>i?x:{...x,end:Math.min(30,e.currentTarget.duration)}))}}/></div><div className="hint">Aperçu 9:16 • 1080 × 1920</div></section><section className="panel render"><h2><Upload/> Export</h2><div className="spec"><span>Format</span><b>TikTok 9:16</b><span>Résolution</span><b>1080 × 1920</b><span>Logo</span><b>Animé aperçu</b><span>Final</span><b>2.7 secondes</b></div><button className="primary" disabled={!video||busy} onClick={exportSeg}>{busy?<LoaderCircle className="spin"/>:<Download/>}{busy?'RENDU EN COURS':'GÉNÉRER LA SÉQUENCE'}</button><div className="load"><div style={{width:`${progress}%`}}/></div><p>{status}</p><small>Le rendu est effectué dans ton navigateur. Aucun fichier vidéo n'est envoyé par cette V1.</small></section></main><img ref={logo} src="/logo.png" hidden/><img ref={final} src="/final.png" hidden/></div>}
createRoot(document.getElementById('root')).render(<App/>);
